name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          tags: lokinet-proxy:latest

      - name: Create and run container
        id: create_and_run_container
        run: |
          docker run -d \
            --name lokinet-proxy \
            --cap-add NET_ADMIN \
            --device /dev/net/tun:/dev/net/tun \
            --sysctl net.ipv6.conf.all.disable_ipv6=0 \
            -p 127.0.0.1:1051:1051 \
            -v lokinet-data:/var/lib/lokinet \
            lokinet-proxy:latest

          echo 'Waiting 5 minutes for Lokinet to establish network connectivity'
          sleep 300

      - name: Check http://blocks.loki
        if: ${{ !cancelled() && steps.create_and_run_container.outcome == 'success' }}
        run: |
          curl -fsS --proxy socks5h://127.0.0.1:1051 http://blocks.loki | grep -qF 'Blockchain Explorer'

      - name: Check https://blocks.loki
        if: ${{ !cancelled() && steps.create_and_run_container.outcome == 'success' }}
        run: |
          # -k to skip the certificate verification
          # because blocks.loki is not listed in the certificate
          curl -kfsS --proxy socks5h://127.0.0.1:1051 https://blocks.loki | grep -qF 'FLIP TOKEN AIRDROP'

      - name: Check exit node IP
        if: ${{ !cancelled() && steps.create_and_run_container.outcome == 'success' }}
        run: |
          IP=$(curl -fsS --proxy socks5h://127.0.0.1:1051 https://myip.sk/plain)
          EXPECTED_IP='199.195.253.224'

          echo "Exit node IP: $IP"
          echo "Expected exit node IP: $EXPECTED_IP"

          if [ "$IP" != "$EXPECTED_IP" ]; then
            echo 'Unexpected exit node IP'
            exit 1
          else
            echo 'Exit node IP is correct'
          fi

      - name: Stop and remove container
        if: ${{ !cancelled() && steps.create_and_run_container.outcome == 'success' }}
        run: |
          docker stop lokinet-proxy
          docker rm lokinet-proxy